import React from 'react';

const Footer = () => {
  return (
    <footer className="bg-primary text-text-base py-4 text-center absolute bottom-0 w-full">
      <p className="text-sm">© {new Date().getFullYear()} Vlad's Leadership Profile | Generated by AI Career Strategist</p>
    </footer>
  );
};

export default Footer;
